image: openjdk:17-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x ./gradlew
  - mv gradle.properties.example gradle.properties

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - build
    - .gradle

build:
  stage: build
  script: ./gradlew --build-cache assemble

test:
  stage: test
  script: ./gradlew check

publish snapshot:
  stage: publish
