name: Build and Test with Gradle

on:
  push:
    branches-ignore: [ 'main', 'develop' ]
    tags-ignore: [ "*" ]

env:
  CACHE_REV: "1"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace}}/build/
            ${{ github.workspace}}/.gradle/
          key: "${{ runner.os }}-build-${{ env.CACHE_REV }}-${{ hashFiles('**/*.gradle*') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_REV }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup workspace
        run: |
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          cp gradle.properties.example gradle.properties
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew --build-cache assemble --stacktrace
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace}}/build/
            ${{ github.workspace}}/.gradle/
          key: "${{ runner.os }}-build-${{ env.CACHE_REV }}-${{ hashFiles('**/*.gradle*') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_REV }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup workspace
        run: |
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          cp gradle.properties.example gradle.properties
      - name: Test with Gradle
        run: chmod +x ./gradlew && ./gradlew check --stacktrace